# Help:  https://aka.ms/yaml

resources:
- repo: self

variables:  []

trigger:
- master

stages:
  - stage:  build
    dependsOn:  []
    variables:  []
    jobs:
    - job:  main
      dependsOn:  []
      variables:  []
      continueOnError:  false
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Publish "template" artefact
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: template'
        inputs:
          PathtoPublish: template
          ArtifactName: template
  - stage:  release
    dependsOn:  build
    variables:  []
    jobs:
    - job:  main
      dependsOn:  []
      variables:
        location: northcentralus
        rg: blog
      pool:
        vmImage: ubuntu-latest
      steps:
      # Don't checkout repo
      - checkout: none
      # Download artefact from previous stage
      - download: current
        artifact: template
      # Deploy ARM template from artefact files
      - task: AzureResourceGroupDeployment@2
        displayName: Azure Deployment - deploy.json
        inputs:
          azureSubscription: devops-deploy
          resourceGroupName: $(rg)
          location: '$(location)'
          templateLocation:  Linked artifact
          csmFile: $(Pipeline.Workspace)/template/deploy.json
          csmParametersFile: $(Pipeline.Workspace)/template/deploy.prod.parameters.json
          overrideParameters: ''
        timeoutInMinutes: 3
